one = 3
two = 3
three = 5
four = 4
five = 4
six = 3
seven = 5
eight = 5
nine = 4
ten = 3
eleven = 6
twelve = 6
thirteen = 8
fourteen = 8
fifteen = 7
sixteen = 7
seventeen = 9
eighteen = 8
nineteen = 8
twenty = 6
thirty = 6
forty = 5
fifty = 5
sixty = 5
seventy = 7
eighty = 6
ninety = 6
hundred = 7
a = 3
thousand = 8

b = one + two + three + four + five + six + seven + eight + nine
teens = ten + eleven + twelve + thirteen + fourteen + fifteen + sixteen + seventeen + eighteen + nineteen
ts = twenty + thirty + forty + fifty + sixty + seventy + eighty + ninety
f99 = 9*b + teens + ts*10
ans = (one + thousand) + 10*f99 + (b + 9*hundred) + 99*b + (hundred + a)*99*9
print(ans)